navbar:
  blog_title: Xrellana
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "rss", name: "RSS", link: "/atom.xml", icon: "iconfont icon-rss-fill" }

index:
  slogan:
    enable: true
    text: RANDOM THOUGHTS


favicon: /img/favicon.png
apple_touch_icon: /img/apple-touch-icon.png
